# Default values for rando.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: aransh/rando
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

env:
  interval: 60 # In seconds
  count: 25
  maxNum: 50

podAnnotations: {}

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi