version: "3.7"

services:

  jenkins:
    build:
      context: ./
      dockerfile: Dockerfile.jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      restart: always
    container_name: jenkins
    volumes:
      - /home/nathan/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend
      - backend

  # nginx:
  #   image: nginx:1.21.4
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     # - ./src/main/webapp/:/usr/share/nginx/html/
  #     # - ./src/main/webapp/:/usr/share/nginx/html/static/
  #   ports:
  #     - "80:80"
  #   networks:
  #     - frontend


volumes:
  logs:
  data:
  config:

networks:
  frontend:
  backend: